export { default as CategoryManagement } from "./CategoryManagement";
export { default as CommentManagement } from "./CommentManagement";
export { default as DescriptionManagement } from "./DescriptionManagement";
export { default as DiscountManagement } from "./DiscountManagement";
export { default as OrderManagement } from "./OrderManagement";
export { default as PostManagement } from "./PostManagement";
export { default as ProductManagement } from "./ProductManagement";
export { default as SliderManagement } from "./SliderManagement";
export { default as RoleManagement } from "./RoleManagement";