export { default as CategoryManagement } from "./CategoryManagement";
export { default as CommentManagement } from "./CommentManagement";
export { default as DiscountManagement } from "./DiscountManagement";
export { default as PostManagement } from "./PostManagement";
export { default as ProductManagement } from "./ProductManagement";
export { default as SliderManagement } from "./SliderManagement";
export { default as RoleManagement } from "./RoleManagement";
export { default as AccessManagement } from "./AccessManagement.jsx";
export { default as ContractManagement } from "./ContractManagement.jsx";
;
